import json
import logging
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

def format_rag_response(
    question: str,
    answer: str,
    chunks: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """
    Structures the query results, LLM output, and source context into a standard dictionary format.

    Args:
        question: User query string.
        answer: Text response generated by the LLM.
        chunks: List of retrieved (and potentially re-ranked) text chunks.

    Returns:
        Structured dictionary matching Member 3 specifications.
    """
    logger.info("Formatting response...")
    
    # Extract unique source resume filenames
    sources = sorted(list(set(chunk.get("resume_file", "") for chunk in chunks if chunk.get("resume_file"))))
    
    # Collect similarity scores (use rerank_score if present, otherwise fallback to FAISS similarity score)
    similarity_scores = []
    for chunk in chunks:
        score = chunk.get("rerank_score")
        if score is None:
            score = chunk.get("score", 0.0)
        similarity_scores.append(float(score))

    # Package clean chunk information for representation
    formatted_chunks = []
    for chunk in chunks:
        formatted_chunk = {
            "candidate_name": chunk.get("candidate_name", ""),
            "resume_file": chunk.get("resume_file", ""),
            "chunk_id": chunk.get("chunk_id", -1),
            "text": chunk.get("text", ""),
            "score": float(chunk.get("score", 0.0))
        }
        # Add rerank score if it was computed
        if "rerank_score" in chunk:
            formatted_chunk["rerank_score"] = float(chunk["rerank_score"])
            
        formatted_chunks.append(formatted_chunk)

    return {
        "question": question,
        "answer": answer,
        "retrieved_chunks": formatted_chunks,
        "sources": sources,
        "similarity_scores": similarity_scores
    }

def response_to_json_string(response_dict: Dict[str, Any], indent: int = 4) -> str:
    """
    Serializes a response dictionary into a pretty-printed, indented JSON string.
    """
    try:
        return json.dumps(response_dict, indent=indent, ensure_ascii=False)
    except Exception as e:
        logger.error(f"Failed to serialize response dict to JSON: {e}")
        return json.dumps({
            "error": "Failed to format response as JSON.",
            "question": response_dict.get("question", ""),
            "answer": response_dict.get("answer", "")
        }, indent=indent)
